version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "llm-response-evaluator"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket"
s3_prefix = "llm-response-evaluator"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=dev BedrockModelAccess=true"
image_repositories = []

[default.build]
[default.build.parameters]
use_container = true